[package]
name = "jrsonnet-cli"
description = "Utilities for building jrsonnet CLIs"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
exp-preserve-order = [
    "jrsonnet-evaluator/exp-preserve-order",
    "jrsonnet-stdlib/exp-preserve-order",
]
exp-bigint = [
    "jrsonnet-evaluator/exp-bigint",
    "jrsonnet-stdlib/exp-bigint",
]
exp-fqname = [
    "jrsonnet-stdlib/exp-fqname",
]
exp-null-coaelse = [
    "jrsonnet-evaluator/exp-null-coaelse",
    "jrsonnet-stdlib/exp-null-coaelse",
]
legacy-this-file = ["jrsonnet-stdlib/legacy-this-file"]

[dependencies]
jrsonnet-evaluator = { workspace = true, features = ["explaining-traces"] }
jrsonnet-parser.workspace = true
jrsonnet-stdlib.workspace = true
jrsonnet-gcmodule.workspace = true

clap = { workspace = true, features = ["derive"] }
